name: Android CI (Debug)

on:
  push:
    branches: [ "master"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # 安装 Android SDK + 接受 license（会自动配置 ANDROID_SDK_ROOT）
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Gradle 缓存（含依赖、构建缓存）
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 可选：显示 Gradle 与 AGP 版本，便于调试日志
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Show Gradle info
        run: ./gradlew -v

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Upload assets to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v1.0.0"
          files: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/mapping/release/mapping.txt
