name: Publish Debug APK to Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag name (e.g., v1.0.0)"
        required: true

permissions:
  contents: write   # 允许创建/更新 Release

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v2

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: android-actions/setup-android@v3
      - uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Show outputs (debug)
        run: ls -R app/build/outputs || true

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          generate_release_notes: true
          files: |
            app/build/outputs/apk/debug/*.apk
